api_platform:
    title: 'Symfony REST API'
    description: 'A Symfony API to manage a web app.'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        multipart: ['multipart/form-data']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: true
            page_parameter_name: _page
            items_per_page: 4